//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.Models
{
    public partial class Car
    {
        #region Primitive Properties
    
        public virtual decimal Id
        {
            get;
            set;
        }
    
        public virtual decimal CarTypeId
        {
            get;
            set;
        }
    
        public virtual string CarLicensePlate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual CarType CarType
        {
            get { return _carType; }
            set
            {
                if (!ReferenceEquals(_carType, value))
                {
                    var previousValue = _carType;
                    _carType = value;
                    FixupCarType(previousValue);
                }
            }
        }
        private CarType _carType;

        #endregion
        #region Association Fixup
    
        private void FixupCarType(CarType previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Car, this))
            {
                previousValue.Car = null;
            }
    
            if (CarType != null)
            {
                CarType.Car = this;
            }
        }

        #endregion
    }
}
