//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.Models
{
    public partial class CarType
    {
        #region Primitive Properties
    
        public virtual decimal Id
        {
            get;
            set;
        }
    
        public virtual string CarTypeName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Car Car
        {
            get { return _car; }
            set
            {
                if (!ReferenceEquals(_car, value))
                {
                    var previousValue = _car;
                    _car = value;
                    FixupCar(previousValue);
                }
            }
        }
        private Car _car;

        #endregion
        #region Association Fixup
    
        private void FixupCar(Car previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.CarType, this))
            {
                previousValue.CarType = null;
            }
    
            if (Car != null)
            {
                Car.CarType = this;
            }
        }

        #endregion
    }
}
