//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace DAL.Models
{
    public partial class TOCPPEntities : ObjectContext
    {
        public const string ConnectionString = "name=TOCPPEntities";
        public const string ContainerName = "TOCPPEntities";
    
        #region Constructors
    
        public TOCPPEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public TOCPPEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public TOCPPEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<DeliveryNotes> DeliveryNotes
        {
            get { return _deliveryNotes  ?? (_deliveryNotes = CreateObjectSet<DeliveryNotes>("DeliveryNotes")); }
        }
        private ObjectSet<DeliveryNotes> _deliveryNotes;
    
        public ObjectSet<ReceitpNote> ReceitpNotes
        {
            get { return _receitpNotes  ?? (_receitpNotes = CreateObjectSet<ReceitpNote>("ReceitpNotes")); }
        }
        private ObjectSet<ReceitpNote> _receitpNotes;
    
        public ObjectSet<Worker> Workers
        {
            get { return _workers  ?? (_workers = CreateObjectSet<Worker>("Workers")); }
        }
        private ObjectSet<Worker> _workers;
    
        public ObjectSet<LocationType> LocationTypes
        {
            get { return _locationTypes  ?? (_locationTypes = CreateObjectSet<LocationType>("LocationTypes")); }
        }
        private ObjectSet<LocationType> _locationTypes;
    
        public ObjectSet<Location> Locations
        {
            get { return _locations  ?? (_locations = CreateObjectSet<Location>("Locations")); }
        }
        private ObjectSet<Location> _locations;
    
        public ObjectSet<Method> Methods
        {
            get { return _methods  ?? (_methods = CreateObjectSet<Method>("Methods")); }
        }
        private ObjectSet<Method> _methods;
    
        public ObjectSet<Car> Cars
        {
            get { return _cars  ?? (_cars = CreateObjectSet<Car>("Cars")); }
        }
        private ObjectSet<Car> _cars;
    
        public ObjectSet<CarType> CarTypes
        {
            get { return _carTypes  ?? (_carTypes = CreateObjectSet<CarType>("CarTypes")); }
        }
        private ObjectSet<CarType> _carTypes;
    
        public ObjectSet<NoteLineItem> NoteLineItemSet
        {
            get { return _noteLineItemSet  ?? (_noteLineItemSet = CreateObjectSet<NoteLineItem>("NoteLineItemSet")); }
        }
        private ObjectSet<NoteLineItem> _noteLineItemSet;

        #endregion
    }
}
