//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.Models
{
    public partial class Method
    {
        #region Primitive Properties
    
        public virtual decimal Id
        {
            get;
            set;
        }
    
        public virtual string MethodName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Worker Worker
        {
            get { return _worker; }
            set
            {
                if (!ReferenceEquals(_worker, value))
                {
                    var previousValue = _worker;
                    _worker = value;
                    FixupWorker(previousValue);
                }
            }
        }
        private Worker _worker;

        #endregion
        #region Association Fixup
    
        private void FixupWorker(Worker previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Method, this))
            {
                previousValue.Method = null;
            }
    
            if (Worker != null)
            {
                Worker.Method = this;
            }
        }

        #endregion
    }
}
