//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Manee.INV.DAL.Models
{
    public partial class NoteLineItem
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string ItemCode
        {
            get;
            set;
        }
    
        public virtual string ItemName
        {
            get;
            set;
        }
    
        public virtual string ItemStatus
        {
            get;
            set;
        }
    
        public virtual string Qty
        {
            get;
            set;
        }
    
        public virtual string Unit
        {
            get;
            set;
        }
    
        public virtual string KindOfItem
        {
            get;
            set;
        }
    
        public virtual int DeliveryNoteId
        {
            get { return _deliveryNoteId; }
            set
            {
                if (_deliveryNoteId != value)
                {
                    if (DeliveryNote != null && DeliveryNote.Id != value)
                    {
                        DeliveryNote = null;
                    }
                    _deliveryNoteId = value;
                }
            }
        }
        private int _deliveryNoteId;

        #endregion
        #region Navigation Properties
    
        public virtual DeliveryNote DeliveryNote
        {
            get { return _deliveryNote; }
            set
            {
                if (!ReferenceEquals(_deliveryNote, value))
                {
                    var previousValue = _deliveryNote;
                    _deliveryNote = value;
                    FixupDeliveryNote(previousValue);
                }
            }
        }
        private DeliveryNote _deliveryNote;

        #endregion
        #region Association Fixup
    
        private void FixupDeliveryNote(DeliveryNote previousValue)
        {
            if (previousValue != null && previousValue.NoteLineItems.Contains(this))
            {
                previousValue.NoteLineItems.Remove(this);
            }
    
            if (DeliveryNote != null)
            {
                if (!DeliveryNote.NoteLineItems.Contains(this))
                {
                    DeliveryNote.NoteLineItems.Add(this);
                }
                if (DeliveryNoteId != DeliveryNote.Id)
                {
                    DeliveryNoteId = DeliveryNote.Id;
                }
            }
        }

        #endregion
    }
}
