//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Manee.INV.DAL.Models
{
    public partial class ReceiptNote
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (DeliveryNote != null && DeliveryNote.Id != value)
                    {
                        DeliveryNote = null;
                    }
                    _id = value;
                }
            }
        }
        private int _id;
    
        public virtual Nullable<int> DeliveryNoteId
        {
            get;
            set;
        }
    
        public virtual string ReceiverName
        {
            get;
            set;
        }
    
        public virtual string ReceiverCode
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual DeliveryNote DeliveryNote
        {
            get { return _deliveryNote; }
            set
            {
                if (!ReferenceEquals(_deliveryNote, value))
                {
                    var previousValue = _deliveryNote;
                    _deliveryNote = value;
                    FixupDeliveryNote(previousValue);
                }
            }
        }
        private DeliveryNote _deliveryNote;

        #endregion
        #region Association Fixup
    
        private void FixupDeliveryNote(DeliveryNote previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.ReceiptNote, this))
            {
                previousValue.ReceiptNote = null;
            }
    
            if (DeliveryNote != null)
            {
                DeliveryNote.ReceiptNote = this;
                if (Id != DeliveryNote.Id)
                {
                    Id = DeliveryNote.Id;
                }
            }
        }

        #endregion
    }
}
