//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL.Models
{
    public partial class ReceitpNote
    {
        #region Primitive Properties
    
        public virtual decimal Id
        {
            get;
            set;
        }
    
        public virtual string Code
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> DeliveryNoteId
        {
            get;
            set;
        }
    
        public virtual string ReceiverCode
        {
            get;
            set;
        }
    
        public virtual string ReceiverName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ReceiveDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual DeliveryNotes DeliveryNotes
        {
            get { return _deliveryNotes; }
            set
            {
                if (!ReferenceEquals(_deliveryNotes, value))
                {
                    var previousValue = _deliveryNotes;
                    _deliveryNotes = value;
                    FixupDeliveryNotes(previousValue);
                }
            }
        }
        private DeliveryNotes _deliveryNotes;

        #endregion
        #region Association Fixup
    
        private void FixupDeliveryNotes(DeliveryNotes previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.ReceitpNote, this))
            {
                previousValue.ReceitpNote = null;
            }
    
            if (DeliveryNotes != null)
            {
                DeliveryNotes.ReceitpNote = this;
            }
        }

        #endregion
    }
}
