//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Manee.INV.DB.Models
{
    public partial class LocationType
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string LocationType1
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Location> Locations
        {
            get
            {
                if (_locations == null)
                {
                    var newCollection = new FixupCollection<Location>();
                    newCollection.CollectionChanged += FixupLocations;
                    _locations = newCollection;
                }
                return _locations;
            }
            set
            {
                if (!ReferenceEquals(_locations, value))
                {
                    var previousValue = _locations as FixupCollection<Location>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLocations;
                    }
                    _locations = value;
                    var newValue = value as FixupCollection<Location>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLocations;
                    }
                }
            }
        }
        private ICollection<Location> _locations;

        #endregion
        #region Association Fixup
    
        private void FixupLocations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Location item in e.NewItems)
                {
                    item.LocationType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Location item in e.OldItems)
                {
                    if (ReferenceEquals(item.LocationType, this))
                    {
                        item.LocationType = null;
                    }
                }
            }
        }

        #endregion
    }
}
