//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public decimal Id { get; set; }
        public decimal CarTypeId { get; set; }
        public string CarLicensePlate { get; set; }
        public decimal CarTypes_Id { get; set; }
    }
}
