//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteLineItemSet
    {
        public decimal Id { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Status { get; set; }
        public Nullable<decimal> DeliveryNoteId { get; set; }
        public decimal DeliveryNotes_Id { get; set; }
    }
}
