//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MvcApplication1.Models
{
    public partial class Doc
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<SampleLineItem> SampleLineItems
        {
            get
            {
                if (_sampleLineItems == null)
                {
                    var newCollection = new FixupCollection<SampleLineItem>();
                    newCollection.CollectionChanged += FixupSampleLineItems;
                    _sampleLineItems = newCollection;
                }
                return _sampleLineItems;
            }
            set
            {
                if (!ReferenceEquals(_sampleLineItems, value))
                {
                    var previousValue = _sampleLineItems as FixupCollection<SampleLineItem>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSampleLineItems;
                    }
                    _sampleLineItems = value;
                    var newValue = value as FixupCollection<SampleLineItem>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSampleLineItems;
                    }
                }
            }
        }
        private ICollection<SampleLineItem> _sampleLineItems;

        #endregion
        #region Association Fixup
    
        private void FixupSampleLineItems(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SampleLineItem item in e.NewItems)
                {
                    item.Doc = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SampleLineItem item in e.OldItems)
                {
                    if (ReferenceEquals(item.Doc, this))
                    {
                        item.Doc = null;
                    }
                }
            }
        }

        #endregion
    }
}
