//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace MvcApplication1.Models
{
    public partial class Model1Container : ObjectContext
    {
        public const string ConnectionString = "name=Model1Container";
        public const string ContainerName = "Model1Container";
    
        #region Constructors
    
        public Model1Container()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Model1Container(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Model1Container(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<SampleLineItem> SampleLineItems
        {
            get { return _sampleLineItems  ?? (_sampleLineItems = CreateObjectSet<SampleLineItem>("SampleLineItems")); }
        }
        private ObjectSet<SampleLineItem> _sampleLineItems;
    
        public ObjectSet<Doc> Docs
        {
            get { return _docs  ?? (_docs = CreateObjectSet<Doc>("Docs")); }
        }
        private ObjectSet<Doc> _docs;
    
        public ObjectSet<MSreplication_options> MSreplication_options
        {
            get { return _mSreplication_options  ?? (_mSreplication_options = CreateObjectSet<MSreplication_options>("MSreplication_options")); }
        }
        private ObjectSet<MSreplication_options> _mSreplication_options;
    
        public ObjectSet<spt_fallback_db> spt_fallback_db
        {
            get { return _spt_fallback_db  ?? (_spt_fallback_db = CreateObjectSet<spt_fallback_db>("spt_fallback_db")); }
        }
        private ObjectSet<spt_fallback_db> _spt_fallback_db;
    
        public ObjectSet<spt_fallback_dev> spt_fallback_dev
        {
            get { return _spt_fallback_dev  ?? (_spt_fallback_dev = CreateObjectSet<spt_fallback_dev>("spt_fallback_dev")); }
        }
        private ObjectSet<spt_fallback_dev> _spt_fallback_dev;
    
        public ObjectSet<spt_fallback_usg> spt_fallback_usg
        {
            get { return _spt_fallback_usg  ?? (_spt_fallback_usg = CreateObjectSet<spt_fallback_usg>("spt_fallback_usg")); }
        }
        private ObjectSet<spt_fallback_usg> _spt_fallback_usg;
    
        public ObjectSet<spt_monitor> spt_monitor
        {
            get { return _spt_monitor  ?? (_spt_monitor = CreateObjectSet<spt_monitor>("spt_monitor")); }
        }
        private ObjectSet<spt_monitor> _spt_monitor;
    
        public ObjectSet<spt_values> spt_values
        {
            get { return _spt_values  ?? (_spt_values = CreateObjectSet<spt_values>("spt_values")); }
        }
        private ObjectSet<spt_values> _spt_values;
    
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get { return _sysdiagrams  ?? (_sysdiagrams = CreateObjectSet<sysdiagram>("sysdiagrams")); }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion
    }
}
