//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MvcApplication1.Models
{
    public partial class MSreplication_options
    {
        #region Primitive Properties
    
        public virtual string optname
        {
            get;
            set;
        }
    
        public virtual bool value
        {
            get;
            set;
        }
    
        public virtual int major_version
        {
            get;
            set;
        }
    
        public virtual int minor_version
        {
            get;
            set;
        }
    
        public virtual int revision
        {
            get;
            set;
        }
    
        public virtual int install_failures
        {
            get;
            set;
        }

        #endregion
    }
}
