//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MvcApplication1.Models
{
    public partial class SampleLineItem
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int DocId
        {
            get { return _docId; }
            set
            {
                if (_docId != value)
                {
                    if (Doc != null && Doc.Id != value)
                    {
                        Doc = null;
                    }
                    _docId = value;
                }
            }
        }
        private int _docId;
    
        public virtual string ItemName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ItemDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Doc Doc
        {
            get { return _doc; }
            set
            {
                if (!ReferenceEquals(_doc, value))
                {
                    var previousValue = _doc;
                    _doc = value;
                    FixupDoc(previousValue);
                }
            }
        }
        private Doc _doc;

        #endregion
        #region Association Fixup
    
        private void FixupDoc(Doc previousValue)
        {
            if (previousValue != null && previousValue.SampleLineItems.Contains(this))
            {
                previousValue.SampleLineItems.Remove(this);
            }
    
            if (Doc != null)
            {
                if (!Doc.SampleLineItems.Contains(this))
                {
                    Doc.SampleLineItems.Add(this);
                }
                if (DocId != Doc.Id)
                {
                    DocId = Doc.Id;
                }
            }
        }

        #endregion
    }
}
