//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MvcApplication1.Models
{
    public partial class spt_fallback_dev
    {
        #region Primitive Properties
    
        public virtual string xserver_name
        {
            get;
            set;
        }
    
        public virtual System.DateTime xdttm_ins
        {
            get;
            set;
        }
    
        public virtual System.DateTime xdttm_last_ins_upd
        {
            get;
            set;
        }
    
        public virtual Nullable<int> xfallback_low
        {
            get;
            set;
        }
    
        public virtual string xfallback_drive
        {
            get;
            set;
        }
    
        public virtual int low
        {
            get;
            set;
        }
    
        public virtual int high
        {
            get;
            set;
        }
    
        public virtual short status
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string phyname
        {
            get;
            set;
        }

        #endregion
    }
}
