//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MvcApplication1.Models
{
    public partial class spt_fallback_usg
    {
        #region Primitive Properties
    
        public virtual string xserver_name
        {
            get;
            set;
        }
    
        public virtual System.DateTime xdttm_ins
        {
            get;
            set;
        }
    
        public virtual System.DateTime xdttm_last_ins_upd
        {
            get;
            set;
        }
    
        public virtual Nullable<int> xfallback_vstart
        {
            get;
            set;
        }
    
        public virtual short dbid
        {
            get;
            set;
        }
    
        public virtual int segmap
        {
            get;
            set;
        }
    
        public virtual int lstart
        {
            get;
            set;
        }
    
        public virtual int sizepg
        {
            get;
            set;
        }
    
        public virtual int vstart
        {
            get;
            set;
        }

        #endregion
    }
}
