//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MvcApplication1.Models
{
    public partial class spt_monitor
    {
        #region Primitive Properties
    
        public virtual System.DateTime lastrun
        {
            get;
            set;
        }
    
        public virtual int cpu_busy
        {
            get;
            set;
        }
    
        public virtual int io_busy
        {
            get;
            set;
        }
    
        public virtual int idle
        {
            get;
            set;
        }
    
        public virtual int pack_received
        {
            get;
            set;
        }
    
        public virtual int pack_sent
        {
            get;
            set;
        }
    
        public virtual int connections
        {
            get;
            set;
        }
    
        public virtual int pack_errors
        {
            get;
            set;
        }
    
        public virtual int total_read
        {
            get;
            set;
        }
    
        public virtual int total_write
        {
            get;
            set;
        }
    
        public virtual int total_errors
        {
            get;
            set;
        }

        #endregion
    }
}
