//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MvcApplication1.Models
{
    public partial class spt_values
    {
        #region Primitive Properties
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual int number
        {
            get;
            set;
        }
    
        public virtual string type
        {
            get;
            set;
        }
    
        public virtual Nullable<int> low
        {
            get;
            set;
        }
    
        public virtual Nullable<int> high
        {
            get;
            set;
        }
    
        public virtual Nullable<int> status
        {
            get;
            set;
        }

        #endregion
    }
}
