//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manee.INV.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNote
    {
        public DeliveryNote()
        {
            this.NoteLineItems = new HashSet<NoteLineItem>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> OriginId { get; set; }
        public Nullable<decimal> DestinationId { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string SenderName { get; set; }
        public string SenderCode { get; set; }
        public string CarType { get; set; }
        public string CarLicensePlate { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<NoteLineItem> NoteLineItems { get; set; }
    }
}
