//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manee.INV.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteLineItem
    {
        public int Id { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual DeliveryNote DeliveryNote { get; set; }
    }
}
