//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MvcApplication2.Models
{
    public partial class DeliveryNote : Document
    {
        #region Primitive Properties
    
        public virtual System.DateTime DeliveryDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<NoteLineItem> NoteLineItems
        {
            get
            {
                if (_noteLineItems == null)
                {
                    var newCollection = new FixupCollection<NoteLineItem>();
                    newCollection.CollectionChanged += FixupNoteLineItems;
                    _noteLineItems = newCollection;
                }
                return _noteLineItems;
            }
            set
            {
                if (!ReferenceEquals(_noteLineItems, value))
                {
                    var previousValue = _noteLineItems as FixupCollection<NoteLineItem>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupNoteLineItems;
                    }
                    _noteLineItems = value;
                    var newValue = value as FixupCollection<NoteLineItem>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupNoteLineItems;
                    }
                }
            }
        }
        private ICollection<NoteLineItem> _noteLineItems;

        #endregion
        #region Association Fixup
    
        private void FixupNoteLineItems(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (NoteLineItem item in e.NewItems)
                {
                    item.DeliveryNote = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (NoteLineItem item in e.OldItems)
                {
                    if (ReferenceEquals(item.DeliveryNote, this))
                    {
                        item.DeliveryNote = null;
                    }
                }
            }
        }

        #endregion
    }
}
