//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace MvcApplication2.Models
{
    public partial class Model1Container : ObjectContext
    {
        public const string ConnectionString = "name=Model1Container";
        public const string ContainerName = "Model1Container";
    
        #region Constructors
    
        public Model1Container()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Model1Container(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Model1Container(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<NoteLineItem> NoteLineItems
        {
            get { return _noteLineItems  ?? (_noteLineItems = CreateObjectSet<NoteLineItem>("NoteLineItems")); }
        }
        private ObjectSet<NoteLineItem> _noteLineItems;
    
        public ObjectSet<Document> Documents
        {
            get { return _documents  ?? (_documents = CreateObjectSet<Document>("Documents")); }
        }
        private ObjectSet<Document> _documents;
    
        public ObjectSet<Car> Cars
        {
            get { return _cars  ?? (_cars = CreateObjectSet<Car>("Cars")); }
        }
        private ObjectSet<Car> _cars;
    
        public ObjectSet<DeliveryNote1> DeliveryNote1
        {
            get { return _deliveryNote1  ?? (_deliveryNote1 = CreateObjectSet<DeliveryNote1>("DeliveryNote1")); }
        }
        private ObjectSet<DeliveryNote1> _deliveryNote1;
    
        public ObjectSet<Location> Locations
        {
            get { return _locations  ?? (_locations = CreateObjectSet<Location>("Locations")); }
        }
        private ObjectSet<Location> _locations;
    
        public ObjectSet<LocationType> LocationTypes
        {
            get { return _locationTypes  ?? (_locationTypes = CreateObjectSet<LocationType>("LocationTypes")); }
        }
        private ObjectSet<LocationType> _locationTypes;
    
        public ObjectSet<NoteLineItem1> NoteLineItem1
        {
            get { return _noteLineItem1  ?? (_noteLineItem1 = CreateObjectSet<NoteLineItem1>("NoteLineItem1")); }
        }
        private ObjectSet<NoteLineItem1> _noteLineItem1;
    
        public ObjectSet<ReceiptNote> ReceiptNotes
        {
            get { return _receiptNotes  ?? (_receiptNotes = CreateObjectSet<ReceiptNote>("ReceiptNotes")); }
        }
        private ObjectSet<ReceiptNote> _receiptNotes;
    
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get { return _sysdiagrams  ?? (_sysdiagrams = CreateObjectSet<sysdiagram>("sysdiagrams")); }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        public ObjectSet<Worker> Workers
        {
            get { return _workers  ?? (_workers = CreateObjectSet<Worker>("Workers")); }
        }
        private ObjectSet<Worker> _workers;

        #endregion
    }
}
