//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model1", "DeliveryNoteNoteLineItem", "DeliveryNote", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApplication2.Models.DeliveryNote), "NoteLineItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.NoteLineItem), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK_DeliveryNote_Car", "Car", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcApplication2.Models.Car), "DeliveryNote1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.DeliveryNote1), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK_DeliveryNote_Location", "Location", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcApplication2.Models.Location), "DeliveryNote1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.DeliveryNote1), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK_DeliveryNote_Location1", "Location", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcApplication2.Models.Location), "DeliveryNote1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.DeliveryNote1), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK_DeliveryNote_User", "Worker", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcApplication2.Models.Worker), "DeliveryNote1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.DeliveryNote1), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK_DeliveryNote_User1", "Worker", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcApplication2.Models.Worker), "DeliveryNote1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.DeliveryNote1), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK_NoteLineItem_DeliveryNote", "DeliveryNote1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcApplication2.Models.DeliveryNote1), "NoteLineItem1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.NoteLineItem1), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK_ReceiptNote_DeliveryNote", "DeliveryNote1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcApplication2.Models.DeliveryNote1), "ReceiptNote", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.ReceiptNote), true)]
[assembly: EdmRelationshipAttribute("Model1", "FK_Location_LocationType", "LocationType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcApplication2.Models.LocationType), "Location", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication2.Models.Location), true)]

#endregion

namespace MvcApplication2.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NoteLineItem> NoteLineItems
        {
            get
            {
                if ((_NoteLineItems == null))
                {
                    _NoteLineItems = base.CreateObjectSet<NoteLineItem>("NoteLineItems");
                }
                return _NoteLineItems;
            }
        }
        private ObjectSet<NoteLineItem> _NoteLineItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Document> Documents
        {
            get
            {
                if ((_Documents == null))
                {
                    _Documents = base.CreateObjectSet<Document>("Documents");
                }
                return _Documents;
            }
        }
        private ObjectSet<Document> _Documents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Car> Cars
        {
            get
            {
                if ((_Cars == null))
                {
                    _Cars = base.CreateObjectSet<Car>("Cars");
                }
                return _Cars;
            }
        }
        private ObjectSet<Car> _Cars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DeliveryNote1> DeliveryNote1
        {
            get
            {
                if ((_DeliveryNote1 == null))
                {
                    _DeliveryNote1 = base.CreateObjectSet<DeliveryNote1>("DeliveryNote1");
                }
                return _DeliveryNote1;
            }
        }
        private ObjectSet<DeliveryNote1> _DeliveryNote1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Location> Locations
        {
            get
            {
                if ((_Locations == null))
                {
                    _Locations = base.CreateObjectSet<Location>("Locations");
                }
                return _Locations;
            }
        }
        private ObjectSet<Location> _Locations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LocationType> LocationTypes
        {
            get
            {
                if ((_LocationTypes == null))
                {
                    _LocationTypes = base.CreateObjectSet<LocationType>("LocationTypes");
                }
                return _LocationTypes;
            }
        }
        private ObjectSet<LocationType> _LocationTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NoteLineItem1> NoteLineItem1
        {
            get
            {
                if ((_NoteLineItem1 == null))
                {
                    _NoteLineItem1 = base.CreateObjectSet<NoteLineItem1>("NoteLineItem1");
                }
                return _NoteLineItem1;
            }
        }
        private ObjectSet<NoteLineItem1> _NoteLineItem1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReceiptNote> ReceiptNotes
        {
            get
            {
                if ((_ReceiptNotes == null))
                {
                    _ReceiptNotes = base.CreateObjectSet<ReceiptNote>("ReceiptNotes");
                }
                return _ReceiptNotes;
            }
        }
        private ObjectSet<ReceiptNote> _ReceiptNotes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Worker> Workers
        {
            get
            {
                if ((_Workers == null))
                {
                    _Workers = base.CreateObjectSet<Worker>("Workers");
                }
                return _Workers;
            }
        }
        private ObjectSet<Worker> _Workers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NoteLineItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNoteLineItems(NoteLineItem noteLineItem)
        {
            base.AddObject("NoteLineItems", noteLineItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Documents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDocuments(Document document)
        {
            base.AddObject("Documents", document);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCars(Car car)
        {
            base.AddObject("Cars", car);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DeliveryNote1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDeliveryNote1(DeliveryNote1 deliveryNote1)
        {
            base.AddObject("DeliveryNote1", deliveryNote1);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Locations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocations(Location location)
        {
            base.AddObject("Locations", location);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LocationTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocationTypes(LocationType locationType)
        {
            base.AddObject("LocationTypes", locationType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NoteLineItem1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNoteLineItem1(NoteLineItem1 noteLineItem1)
        {
            base.AddObject("NoteLineItem1", noteLineItem1);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReceiptNotes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReceiptNotes(ReceiptNote receiptNote)
        {
            base.AddObject("ReceiptNotes", receiptNote);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Workers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkers(Worker worker)
        {
            base.AddObject("Workers", worker);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Car")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Car : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Car object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Car CreateCar(global::System.Int32 id)
        {
            Car car = new Car();
            car.Id = id;
            return car;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LicensePlateId
        {
            get
            {
                return _LicensePlateId;
            }
            set
            {
                OnLicensePlateIdChanging(value);
                ReportPropertyChanging("LicensePlateId");
                _LicensePlateId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LicensePlateId");
                OnLicensePlateIdChanged();
            }
        }
        private global::System.String _LicensePlateId;
        partial void OnLicensePlateIdChanging(global::System.String value);
        partial void OnLicensePlateIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_DeliveryNote_Car", "DeliveryNote1")]
        public EntityCollection<DeliveryNote1> DeliveryNotes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DeliveryNote1>("Model1.FK_DeliveryNote_Car", "DeliveryNote1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DeliveryNote1>("Model1.FK_DeliveryNote_Car", "DeliveryNote1", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="DeliveryNote")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DeliveryNote : Document
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DeliveryNote object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="docType">Initial value of the DocType property.</param>
        /// <param name="deliveryDate">Initial value of the DeliveryDate property.</param>
        public static DeliveryNote CreateDeliveryNote(global::System.Int32 id, global::System.TimeSpan docType, global::System.DateTime deliveryDate)
        {
            DeliveryNote deliveryNote = new DeliveryNote();
            deliveryNote.Id = id;
            deliveryNote.DocType = docType;
            deliveryNote.DeliveryDate = deliveryDate;
            return deliveryNote;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DeliveryDate
        {
            get
            {
                return _DeliveryDate;
            }
            set
            {
                OnDeliveryDateChanging(value);
                ReportPropertyChanging("DeliveryDate");
                _DeliveryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryDate");
                OnDeliveryDateChanged();
            }
        }
        private global::System.DateTime _DeliveryDate;
        partial void OnDeliveryDateChanging(global::System.DateTime value);
        partial void OnDeliveryDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "DeliveryNoteNoteLineItem", "NoteLineItem")]
        public EntityCollection<NoteLineItem> NoteLineItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NoteLineItem>("Model1.DeliveryNoteNoteLineItem", "NoteLineItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NoteLineItem>("Model1.DeliveryNoteNoteLineItem", "NoteLineItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="DeliveryNote1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DeliveryNote1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DeliveryNote1 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static DeliveryNote1 CreateDeliveryNote1(global::System.Int32 id)
        {
            DeliveryNote1 deliveryNote1 = new DeliveryNote1();
            deliveryNote1.Id = id;
            return deliveryNote1;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sender
        {
            get
            {
                return _Sender;
            }
            set
            {
                OnSenderChanging(value);
                ReportPropertyChanging("Sender");
                _Sender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sender");
                OnSenderChanged();
            }
        }
        private Nullable<global::System.Int32> _Sender;
        partial void OnSenderChanging(Nullable<global::System.Int32> value);
        partial void OnSenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Reciever
        {
            get
            {
                return _Reciever;
            }
            set
            {
                OnRecieverChanging(value);
                ReportPropertyChanging("Reciever");
                _Reciever = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Reciever");
                OnRecieverChanged();
            }
        }
        private Nullable<global::System.Int32> _Reciever;
        partial void OnRecieverChanging(Nullable<global::System.Int32> value);
        partial void OnRecieverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Origin
        {
            get
            {
                return _Origin;
            }
            set
            {
                OnOriginChanging(value);
                ReportPropertyChanging("Origin");
                _Origin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Origin");
                OnOriginChanged();
            }
        }
        private Nullable<global::System.Int32> _Origin;
        partial void OnOriginChanging(Nullable<global::System.Int32> value);
        partial void OnOriginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Destination
        {
            get
            {
                return _Destination;
            }
            set
            {
                OnDestinationChanging(value);
                ReportPropertyChanging("Destination");
                _Destination = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Destination");
                OnDestinationChanged();
            }
        }
        private Nullable<global::System.Int32> _Destination;
        partial void OnDestinationChanging(Nullable<global::System.Int32> value);
        partial void OnDestinationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CarId
        {
            get
            {
                return _CarId;
            }
            set
            {
                OnCarIdChanging(value);
                ReportPropertyChanging("CarId");
                _CarId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarId");
                OnCarIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CarId;
        partial void OnCarIdChanging(Nullable<global::System.Int32> value);
        partial void OnCarIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeliveryDate
        {
            get
            {
                return _DeliveryDate;
            }
            set
            {
                OnDeliveryDateChanging(value);
                ReportPropertyChanging("DeliveryDate");
                _DeliveryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryDate");
                OnDeliveryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeliveryDate;
        partial void OnDeliveryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDeliveryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReceiveDate
        {
            get
            {
                return _ReceiveDate;
            }
            set
            {
                OnReceiveDateChanging(value);
                ReportPropertyChanging("ReceiveDate");
                _ReceiveDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReceiveDate");
                OnReceiveDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReceiveDate;
        partial void OnReceiveDateChanging(Nullable<global::System.DateTime> value);
        partial void OnReceiveDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TDate
        {
            get
            {
                return _TDate;
            }
            set
            {
                OnTDateChanging(value);
                ReportPropertyChanging("TDate");
                _TDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TDate");
                OnTDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _TDate;
        partial void OnTDateChanging(Nullable<global::System.DateTime> value);
        partial void OnTDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Driver
        {
            get
            {
                return _Driver;
            }
            set
            {
                OnDriverChanging(value);
                ReportPropertyChanging("Driver");
                _Driver = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Driver");
                OnDriverChanged();
            }
        }
        private global::System.String _Driver;
        partial void OnDriverChanging(global::System.String value);
        partial void OnDriverChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_DeliveryNote_Car", "Car")]
        public Car Car
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Car>("Model1.FK_DeliveryNote_Car", "Car").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Car>("Model1.FK_DeliveryNote_Car", "Car").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Car> CarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Car>("Model1.FK_DeliveryNote_Car", "Car");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Car>("Model1.FK_DeliveryNote_Car", "Car", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_DeliveryNote_Location", "Location")]
        public Location Location
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Location>("Model1.FK_DeliveryNote_Location", "Location").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Location>("Model1.FK_DeliveryNote_Location", "Location").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Location> LocationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Location>("Model1.FK_DeliveryNote_Location", "Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Location>("Model1.FK_DeliveryNote_Location", "Location", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_DeliveryNote_Location1", "Location")]
        public Location Location1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Location>("Model1.FK_DeliveryNote_Location1", "Location").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Location>("Model1.FK_DeliveryNote_Location1", "Location").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Location> Location1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Location>("Model1.FK_DeliveryNote_Location1", "Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Location>("Model1.FK_DeliveryNote_Location1", "Location", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_DeliveryNote_User", "Worker")]
        public Worker Worker
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Worker>("Model1.FK_DeliveryNote_User", "Worker").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Worker>("Model1.FK_DeliveryNote_User", "Worker").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Worker> WorkerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Worker>("Model1.FK_DeliveryNote_User", "Worker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Worker>("Model1.FK_DeliveryNote_User", "Worker", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_DeliveryNote_User1", "Worker")]
        public Worker Worker1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Worker>("Model1.FK_DeliveryNote_User1", "Worker").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Worker>("Model1.FK_DeliveryNote_User1", "Worker").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Worker> Worker1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Worker>("Model1.FK_DeliveryNote_User1", "Worker");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Worker>("Model1.FK_DeliveryNote_User1", "Worker", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_NoteLineItem_DeliveryNote", "NoteLineItem1")]
        public EntityCollection<NoteLineItem1> NoteLineItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NoteLineItem1>("Model1.FK_NoteLineItem_DeliveryNote", "NoteLineItem1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NoteLineItem1>("Model1.FK_NoteLineItem_DeliveryNote", "NoteLineItem1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_ReceiptNote_DeliveryNote", "ReceiptNote")]
        public EntityCollection<ReceiptNote> ReceiptNotes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReceiptNote>("Model1.FK_ReceiptNote_DeliveryNote", "ReceiptNote");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReceiptNote>("Model1.FK_ReceiptNote_DeliveryNote", "ReceiptNote", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Document")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(DeliveryNote))]
    public partial class Document : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Document object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="docType">Initial value of the DocType property.</param>
        public static Document CreateDocument(global::System.Int32 id, global::System.TimeSpan docType)
        {
            Document document = new Document();
            document.Id = id;
            document.DocType = docType;
            return document;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan DocType
        {
            get
            {
                return _DocType;
            }
            set
            {
                OnDocTypeChanging(value);
                ReportPropertyChanging("DocType");
                _DocType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DocType");
                OnDocTypeChanged();
            }
        }
        private global::System.TimeSpan _DocType;
        partial void OnDocTypeChanging(global::System.TimeSpan value);
        partial void OnDocTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Location : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Location object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Location CreateLocation(global::System.Int32 id)
        {
            Location location = new Location();
            location.Id = id;
            return location;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocationTypeId
        {
            get
            {
                return _LocationTypeId;
            }
            set
            {
                OnLocationTypeIdChanging(value);
                ReportPropertyChanging("LocationTypeId");
                _LocationTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationTypeId");
                OnLocationTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _LocationTypeId;
        partial void OnLocationTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnLocationTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_DeliveryNote_Location", "DeliveryNote1")]
        public EntityCollection<DeliveryNote1> DeliveryNotes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DeliveryNote1>("Model1.FK_DeliveryNote_Location", "DeliveryNote1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DeliveryNote1>("Model1.FK_DeliveryNote_Location", "DeliveryNote1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_DeliveryNote_Location1", "DeliveryNote1")]
        public EntityCollection<DeliveryNote1> DeliveryNotes1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DeliveryNote1>("Model1.FK_DeliveryNote_Location1", "DeliveryNote1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DeliveryNote1>("Model1.FK_DeliveryNote_Location1", "DeliveryNote1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_Location_LocationType", "LocationType")]
        public LocationType LocationType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LocationType>("Model1.FK_Location_LocationType", "LocationType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LocationType>("Model1.FK_Location_LocationType", "LocationType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LocationType> LocationTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LocationType>("Model1.FK_Location_LocationType", "LocationType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LocationType>("Model1.FK_Location_LocationType", "LocationType", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="LocationType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LocationType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LocationType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static LocationType CreateLocationType(global::System.Int32 id)
        {
            LocationType locationType = new LocationType();
            locationType.Id = id;
            return locationType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LocationType1
        {
            get
            {
                return _LocationType1;
            }
            set
            {
                OnLocationType1Changing(value);
                ReportPropertyChanging("LocationType1");
                _LocationType1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LocationType1");
                OnLocationType1Changed();
            }
        }
        private global::System.String _LocationType1;
        partial void OnLocationType1Changing(global::System.String value);
        partial void OnLocationType1Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_Location_LocationType", "Location")]
        public EntityCollection<Location> Locations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Location>("Model1.FK_Location_LocationType", "Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Location>("Model1.FK_Location_LocationType", "Location", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="NoteLineItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NoteLineItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NoteLineItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="deliveryNoteId">Initial value of the DeliveryNoteId property.</param>
        public static NoteLineItem CreateNoteLineItem(global::System.Int32 id, global::System.Int32 deliveryNoteId)
        {
            NoteLineItem noteLineItem = new NoteLineItem();
            noteLineItem.Id = id;
            noteLineItem.DeliveryNoteId = deliveryNoteId;
            return noteLineItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeliveryNoteId
        {
            get
            {
                return _DeliveryNoteId;
            }
            set
            {
                OnDeliveryNoteIdChanging(value);
                ReportPropertyChanging("DeliveryNoteId");
                _DeliveryNoteId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryNoteId");
                OnDeliveryNoteIdChanged();
            }
        }
        private global::System.Int32 _DeliveryNoteId;
        partial void OnDeliveryNoteIdChanging(global::System.Int32 value);
        partial void OnDeliveryNoteIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "DeliveryNoteNoteLineItem", "DeliveryNote")]
        public DeliveryNote DeliveryNote
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DeliveryNote>("Model1.DeliveryNoteNoteLineItem", "DeliveryNote").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DeliveryNote>("Model1.DeliveryNoteNoteLineItem", "DeliveryNote").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DeliveryNote> DeliveryNoteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DeliveryNote>("Model1.DeliveryNoteNoteLineItem", "DeliveryNote");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DeliveryNote>("Model1.DeliveryNoteNoteLineItem", "DeliveryNote", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="NoteLineItem1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NoteLineItem1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NoteLineItem1 object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static NoteLineItem1 CreateNoteLineItem1(global::System.Int32 id)
        {
            NoteLineItem1 noteLineItem1 = new NoteLineItem1();
            noteLineItem1.Id = id;
            return noteLineItem1;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemName
        {
            get
            {
                return _ItemName;
            }
            set
            {
                OnItemNameChanging(value);
                ReportPropertyChanging("ItemName");
                _ItemName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemName");
                OnItemNameChanged();
            }
        }
        private global::System.String _ItemName;
        partial void OnItemNameChanging(global::System.String value);
        partial void OnItemNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ItemQty
        {
            get
            {
                return _ItemQty;
            }
            set
            {
                OnItemQtyChanging(value);
                ReportPropertyChanging("ItemQty");
                _ItemQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemQty");
                OnItemQtyChanged();
            }
        }
        private Nullable<global::System.Decimal> _ItemQty;
        partial void OnItemQtyChanging(Nullable<global::System.Decimal> value);
        partial void OnItemQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemUnit
        {
            get
            {
                return _ItemUnit;
            }
            set
            {
                OnItemUnitChanging(value);
                ReportPropertyChanging("ItemUnit");
                _ItemUnit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemUnit");
                OnItemUnitChanged();
            }
        }
        private global::System.String _ItemUnit;
        partial void OnItemUnitChanging(global::System.String value);
        partial void OnItemUnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> KindId
        {
            get
            {
                return _KindId;
            }
            set
            {
                OnKindIdChanging(value);
                ReportPropertyChanging("KindId");
                _KindId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KindId");
                OnKindIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _KindId;
        partial void OnKindIdChanging(Nullable<global::System.Decimal> value);
        partial void OnKindIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DeliveryNoteId
        {
            get
            {
                return _DeliveryNoteId;
            }
            set
            {
                OnDeliveryNoteIdChanging(value);
                ReportPropertyChanging("DeliveryNoteId");
                _DeliveryNoteId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryNoteId");
                OnDeliveryNoteIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DeliveryNoteId;
        partial void OnDeliveryNoteIdChanging(Nullable<global::System.Int32> value);
        partial void OnDeliveryNoteIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_NoteLineItem_DeliveryNote", "DeliveryNote1")]
        public DeliveryNote1 DeliveryNote
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DeliveryNote1>("Model1.FK_NoteLineItem_DeliveryNote", "DeliveryNote1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DeliveryNote1>("Model1.FK_NoteLineItem_DeliveryNote", "DeliveryNote1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DeliveryNote1> DeliveryNoteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DeliveryNote1>("Model1.FK_NoteLineItem_DeliveryNote", "DeliveryNote1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DeliveryNote1>("Model1.FK_NoteLineItem_DeliveryNote", "DeliveryNote1", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="ReceiptNote")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReceiptNote : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReceiptNote object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static ReceiptNote CreateReceiptNote(global::System.Int32 id)
        {
            ReceiptNote receiptNote = new ReceiptNote();
            receiptNote.Id = id;
            return receiptNote;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DeliveryNoteId
        {
            get
            {
                return _DeliveryNoteId;
            }
            set
            {
                OnDeliveryNoteIdChanging(value);
                ReportPropertyChanging("DeliveryNoteId");
                _DeliveryNoteId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryNoteId");
                OnDeliveryNoteIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DeliveryNoteId;
        partial void OnDeliveryNoteIdChanging(Nullable<global::System.Int32> value);
        partial void OnDeliveryNoteIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_ReceiptNote_DeliveryNote", "DeliveryNote1")]
        public DeliveryNote1 DeliveryNote
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DeliveryNote1>("Model1.FK_ReceiptNote_DeliveryNote", "DeliveryNote1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DeliveryNote1>("Model1.FK_ReceiptNote_DeliveryNote", "DeliveryNote1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DeliveryNote1> DeliveryNoteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DeliveryNote1>("Model1.FK_ReceiptNote_DeliveryNote", "DeliveryNote1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DeliveryNote1>("Model1.FK_ReceiptNote_DeliveryNote", "DeliveryNote1", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Worker")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Worker : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Worker object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Worker CreateWorker(global::System.Int32 id)
        {
            Worker worker = new Worker();
            worker.Id = id;
            return worker;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_DeliveryNote_User", "DeliveryNote1")]
        public EntityCollection<DeliveryNote1> DeliveryNotes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DeliveryNote1>("Model1.FK_DeliveryNote_User", "DeliveryNote1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DeliveryNote1>("Model1.FK_DeliveryNote_User", "DeliveryNote1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "FK_DeliveryNote_User1", "DeliveryNote1")]
        public EntityCollection<DeliveryNote1> DeliveryNotes1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DeliveryNote1>("Model1.FK_DeliveryNote_User1", "DeliveryNote1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DeliveryNote1>("Model1.FK_DeliveryNote_User1", "DeliveryNote1", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
