//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MvcApplication2.Models
{
    public partial class NoteLineItem1
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string ItemName
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> ItemQty
        {
            get;
            set;
        }
    
        public virtual string ItemUnit
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> KindId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DeliveryNoteId
        {
            get { return _deliveryNoteId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_deliveryNoteId != value)
                    {
                        if (DeliveryNote != null && DeliveryNote.Id != value)
                        {
                            DeliveryNote = null;
                        }
                        _deliveryNoteId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _deliveryNoteId;

        #endregion
        #region Navigation Properties
    
        public virtual DeliveryNote1 DeliveryNote
        {
            get { return _deliveryNote; }
            set
            {
                if (!ReferenceEquals(_deliveryNote, value))
                {
                    var previousValue = _deliveryNote;
                    _deliveryNote = value;
                    FixupDeliveryNote(previousValue);
                }
            }
        }
        private DeliveryNote1 _deliveryNote;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupDeliveryNote(DeliveryNote1 previousValue)
        {
            if (previousValue != null && previousValue.NoteLineItems.Contains(this))
            {
                previousValue.NoteLineItems.Remove(this);
            }
    
            if (DeliveryNote != null)
            {
                if (!DeliveryNote.NoteLineItems.Contains(this))
                {
                    DeliveryNote.NoteLineItems.Add(this);
                }
                if (DeliveryNoteId != DeliveryNote.Id)
                {
                    DeliveryNoteId = DeliveryNote.Id;
                }
            }
            else if (!_settingFK)
            {
                DeliveryNoteId = null;
            }
        }

        #endregion
    }
}
