//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MvcApplication2.Models
{
    public partial class Worker
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }
    
        public virtual string Code
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<DeliveryNote1> DeliveryNotes
        {
            get
            {
                if (_deliveryNotes == null)
                {
                    var newCollection = new FixupCollection<DeliveryNote1>();
                    newCollection.CollectionChanged += FixupDeliveryNotes;
                    _deliveryNotes = newCollection;
                }
                return _deliveryNotes;
            }
            set
            {
                if (!ReferenceEquals(_deliveryNotes, value))
                {
                    var previousValue = _deliveryNotes as FixupCollection<DeliveryNote1>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupDeliveryNotes;
                    }
                    _deliveryNotes = value;
                    var newValue = value as FixupCollection<DeliveryNote1>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupDeliveryNotes;
                    }
                }
            }
        }
        private ICollection<DeliveryNote1> _deliveryNotes;
    
        public virtual ICollection<DeliveryNote1> DeliveryNotes1
        {
            get
            {
                if (_deliveryNotes1 == null)
                {
                    var newCollection = new FixupCollection<DeliveryNote1>();
                    newCollection.CollectionChanged += FixupDeliveryNotes1;
                    _deliveryNotes1 = newCollection;
                }
                return _deliveryNotes1;
            }
            set
            {
                if (!ReferenceEquals(_deliveryNotes1, value))
                {
                    var previousValue = _deliveryNotes1 as FixupCollection<DeliveryNote1>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupDeliveryNotes1;
                    }
                    _deliveryNotes1 = value;
                    var newValue = value as FixupCollection<DeliveryNote1>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupDeliveryNotes1;
                    }
                }
            }
        }
        private ICollection<DeliveryNote1> _deliveryNotes1;

        #endregion
        #region Association Fixup
    
        private void FixupDeliveryNotes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (DeliveryNote1 item in e.NewItems)
                {
                    item.Worker = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DeliveryNote1 item in e.OldItems)
                {
                    if (ReferenceEquals(item.Worker, this))
                    {
                        item.Worker = null;
                    }
                }
            }
        }
    
        private void FixupDeliveryNotes1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (DeliveryNote1 item in e.NewItems)
                {
                    item.Worker1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DeliveryNote1 item in e.OldItems)
                {
                    if (ReferenceEquals(item.Worker1, this))
                    {
                        item.Worker1 = null;
                    }
                }
            }
        }

        #endregion
    }
}
